services:
  - type: web
    name: moviepage
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn moviepage.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DATABASE_URL
        sync: false