services:
  - type: web
    name: moviepage
    env: python
    plan: free

    # Ensure build.sh exists in your root folder!
    buildCommand: "./build.sh"
    startCommand: "gunicorn moviepage.wsgi:application --bind 0.0.0.0:$PORT"

    autoDeploy: true

    envVars:
      - key: DATABASE_URL
        sync: false # Get this from your Neon DB dashboard

      - key: SECRET_KEY
        generateValue: true

      - key: DEBUG
        value: "False"

      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - key: PYTHON_VERSION
        value: "3.12.1" # Matches your local Python 3.12

      - key: DJANGO_SETTINGS_MODULE
        value: "moviepage.settings"

      # --- ADD THESE FOR CLOUDINARY ---
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false