# Generated by Django 6.0.1 on 2026-03-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
