# Generated by Django 6.0.1 on 2026-03-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_moviepost_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviepost',
            options={'ordering': ['-post_no']},
        ),
    ]
