# Generated by Django 6.0.1 on 2026-01-31 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_moviepost_post_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviepost',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='moviepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='moviepage/'),
        ),
    ]
