# Generated by Django 6.0.1 on 2026-01-31 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_moviepost_view_count_alter_moviepost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviepost',
            name='view_count',
        ),
        migrations.CreateModel(
            name='MovieAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('last_viewed', models.DateTimeField(auto_now=True)),
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='movieapp.moviepost')),
            ],
        ),
    ]
