# Generated by Django 6.0.1 on 2026-03-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_moviepost_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviepost',
            options={'ordering': ['-created_at']},
        ),
    ]
