# Generated by Django 6.0.1 on 2026-02-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_remove_moviepost_view_count_movieanalytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='post_no',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
