# Generated by Django 6.0.1 on 2026-03-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_alter_moviepost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviepost',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='moviepage/'),
        ),
        migrations.AlterField(
            model_name='moviepost',
            name='movie_link',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
