# Generated by Django 6.0.1 on 2026-03-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0005_alter_moviepost_post_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Main Admin'), ('subadmin', 'Sub Admin')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
